MPOL modification request
FreeLoaderz/Submit-API-Registry pull request #95
Opened 2022-07-24 23:42 UTC by gopex21

Modified the json to add our second relay

2022-07-25 23:34 UTC, cxhercules requested changes
Please rebase or pull most resent copy and start from there.

2022-07-25 23:38 UTC, cxhercules commented on spo-links.json
> +        { "url": "http://217.28.30.43:8090/api/submit/tx", "location": "Canada" },
Also tested both endpoints and this one returns this error:
```
Failed
400:
"transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (ValueNotConservedUTxO (Value 0 (fromList [])) (Value 9831683 (fromList []))))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = SafeHash \"a05e800cc2a9e35af273bb774c4ed9b6f70a12077334c4d744ff04987df0e909\"}) 0,TxInCompact (TxId {_unTxId = SafeHash \"a05e800cc2a9e35af273bb774c4ed9b6f70a12077334c4d744ff04987df0e909\"}) 1]))))])"
```

2022-07-25 23:39 UTC, cxhercules commented on spo-links.json
> +        { "url": "http://217.28.30.43:8090/api/submit/tx", "location": "Canada" },
Please check the health of this endpoint and confirm.

2022-07-26 00:39 UTC, gopex21 commented
Hi,

Node was restored and is currently synchronizing.

Will modify the most recent copy

On Mon, 25 Jul 2022 at 19:39, Christian Hercules ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In spo-links.json
> <https://github.com/FreeLoaderz/Submit-API-Registry/pull/95#discussion_r929393825>
> :
>
> > @@ -151,6 +151,10 @@
>        "FAIR": { "links": [
>          { "url": "https://eu01.submit.fairpool.eu/api/submit/tx", "location": "Austria" }
>        ] },
> +      "MPOL": { "links": [
> +        { "url": "http://217.28.30.43:8090/api/submit/tx", "location": "Canada" },
>
> Please check the health of this endpoint and confirm.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/FreeLoaderz/Submit-API-Registry/pull/95#discussion_r929393825>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AXDGLRUESXLGQ6IJ3IQF523VV4QUFANCNFSM54QNVLPA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-07-26 15:03 UTC, closed without merging